<?php

namespace Database\Seeders;

use App\Models\Sparepart;
use Illuminate\Database\Seeder;

class SparepartAcSeeder extends Seeder
{
    /**
     * Seed 20 sparepart AC mobil sesuai data master bengkel.
     * Aman dijalankan berulang kali (idempotent via updateOrCreate).
     */
    public function run(): void
    {
        $spareparts = [
            [
                'kode_part'    => 'AC-001',
                'nama_part'    => 'Kompresor AC Denso',
                'merek'        => 'Denso',
                'kategori'     => 'Kompresor',
                'stok'         => 8,
                'stok_minimum' => 2,
                'harga_beli'   => 2850000,
                'satuan'       => 'pcs',
                'keterangan'   => 'Kompresor AC mobil',
            ],
            [
                'kode_part'    => 'AC-002',
                'nama_part'    => 'Kondensor AC',
                'merek'        => 'Denso',
                'kategori'     => 'Kondensor',
                'stok'         => 12,
                'stok_minimum' => 3,
                'harga_beli'   => 850000,
                'satuan'       => 'pcs',
                'keterangan'   => 'Pendingin freon',
            ],
            [
                'kode_part'    => 'AC-003',
                'nama_part'    => 'Evaporator AC',
                'merek'        => 'Denso',
                'kategori'     => 'Evaporator',
                'stok'         => 10,
                'stok_minimum' => 3,
                'harga_beli'   => 750000,
                'satuan'       => 'pcs',
                'keterangan'   => 'Penyejuk udara kabin',
            ],
            [
                'kode_part'    => 'AC-004',
                'nama_part'    => 'Magnetic Clutch AC',
                'merek'        => 'Denso',
                'kategori'     => 'Kompresor',
                'stok'         => 7,
                'stok_minimum' => 2,
                'harga_beli'   => 650000,
                'satuan'       => 'pcs',
                'keterangan'   => 'Penghubung putaran kompresor',
            ],
            [
                'kode_part'    => 'AC-005',
                'nama_part'    => 'Cooling Fan AC',
                'merek'        => 'Bosch',
                'kategori'     => 'Kelistrikan',
                'stok'         => 9,
                'stok_minimum' => 2,
                'harga_beli'   => 700000,
                'satuan'       => 'pcs',
                'keterangan'   => 'Kipas pendingin kondensor',
            ],
            [
                'kode_part'    => 'AC-006',
                'nama_part'    => 'Filter Dryer AC',
                'merek'        => 'Denso',
                'kategori'     => 'Filter',
                'stok'         => 25,
                'stok_minimum' => 5,
                'harga_beli'   => 150000,
                'satuan'       => 'pcs',
                'keterangan'   => 'Menyaring kotoran dan uap air',
            ],
            [
                'kode_part'    => 'AC-007',
                'nama_part'    => 'Expansion Valve AC',
                'merek'        => 'Sanden',
                'kategori'     => 'Katup',
                'stok'         => 18,
                'stok_minimum' => 5,
                'harga_beli'   => 180000,
                'satuan'       => 'pcs',
                'keterangan'   => 'Mengatur aliran freon',
            ],
            [
                'kode_part'    => 'AC-008',
                'nama_part'    => 'Blower Motor AC',
                'merek'        => 'Bosch',
                'kategori'     => 'Blower',
                'stok'         => 11,
                'stok_minimum' => 3,
                'harga_beli'   => 550000,
                'satuan'       => 'pcs',
                'keterangan'   => 'Menghembuskan udara ke kabin',
            ],
            [
                'kode_part'    => 'AC-009',
                'nama_part'    => 'Pressure Switch AC',
                'merek'        => 'Sanden',
                'kategori'     => 'Sensor',
                'stok'         => 15,
                'stok_minimum' => 4,
                'harga_beli'   => 225000,
                'satuan'       => 'pcs',
                'keterangan'   => 'Sensor tekanan freon',
            ],
            [
                'kode_part'    => 'AC-010',
                'nama_part'    => 'Thermistor Evaporator',
                'merek'        => 'Denso',
                'kategori'     => 'Sensor',
                'stok'         => 14,
                'stok_minimum' => 4,
                'harga_beli'   => 165000,
                'satuan'       => 'pcs',
                'keterangan'   => 'Sensor suhu evaporator',
            ],
            [
                'kode_part'    => 'AC-011',
                'nama_part'    => 'O-Ring AC',
                'merek'        => 'HCC',
                'kategori'     => 'Seal',
                'stok'         => 40,
                'stok_minimum' => 10,
                'harga_beli'   => 50000,
                'satuan'       => 'set',
                'keterangan'   => 'Seal sambungan pipa AC',
            ],
            [
                'kode_part'    => 'AC-012',
                'nama_part'    => 'Selang High Pressure AC',
                'merek'        => 'Gates',
                'kategori'     => 'Selang',
                'stok'         => 30,
                'stok_minimum' => 10,
                'harga_beli'   => 200000,
                'satuan'       => 'meter',
                'keterangan'   => 'Selang tekanan tinggi',
            ],
            [
                'kode_part'    => 'AC-013',
                'nama_part'    => 'Selang Low Pressure AC',
                'merek'        => 'Gates',
                'kategori'     => 'Selang',
                'stok'         => 28,
                'stok_minimum' => 10,
                'harga_beli'   => 180000,
                'satuan'       => 'meter',
                'keterangan'   => 'Selang tekanan rendah',
            ],
            [
                'kode_part'    => 'AC-014',
                'nama_part'    => 'Belt Kompresor AC',
                'merek'        => 'Bando',
                'kategori'     => 'Belt',
                'stok'         => 20,
                'stok_minimum' => 5,
                'harga_beli'   => 120000,
                'satuan'       => 'pcs',
                'keterangan'   => 'Penggerak kompresor AC',
            ],
            [
                'kode_part'    => 'AC-015',
                'nama_part'    => 'Relay Cooling Fan',
                'merek'        => 'Bosch',
                'kategori'     => 'Kelistrikan',
                'stok'         => 16,
                'stok_minimum' => 5,
                'harga_beli'   => 85000,
                'satuan'       => 'pcs',
                'keterangan'   => 'Relay kipas pendingin',
            ],
            [
                'kode_part'    => 'AC-016',
                'nama_part'    => 'Oli Kompresor PAG 46',
                'merek'        => 'Denso',
                'kategori'     => 'Pelumas',
                'stok'         => 12,
                'stok_minimum' => 3,
                'harga_beli'   => 420000,
                'satuan'       => 'liter',
                'keterangan'   => 'Pelumas kompresor AC',
            ],
            [
                'kode_part'    => 'AC-017',
                'nama_part'    => 'Freon R134a',
                'merek'        => 'Honeywell',
                'kategori'     => 'Refrigerant',
                'stok'         => 35,
                'stok_minimum' => 10,
                'harga_beli'   => 320000,
                'satuan'       => 'kg',
                'keterangan'   => 'Refrigeran sistem AC',
            ],
            [
                'kode_part'    => 'AC-018',
                'nama_part'    => 'Isolasi Pipa AC',
                'merek'        => '3M',
                'kategori'     => 'Aksesoris',
                'stok'         => 18,
                'stok_minimum' => 5,
                'harga_beli'   => 65000,
                'satuan'       => 'roll',
                'keterangan'   => 'Pelindung dan peredam pipa',
            ],
            [
                'kode_part'    => 'AC-019',
                'nama_part'    => 'Klem Selang AC',
                'merek'        => 'HCC',
                'kategori'     => 'Aksesoris',
                'stok'         => 22,
                'stok_minimum' => 5,
                'harga_beli'   => 45000,
                'satuan'       => 'set',
                'keterangan'   => 'Pengikat selang AC',
            ],
            [
                'kode_part'    => 'AC-020',
                'nama_part'    => 'Dudukan Kompresor AC',
                'merek'        => 'Toyota Genuine Parts',
                'kategori'     => 'Bracket',
                'stok'         => 6,
                'stok_minimum' => 2,
                'harga_beli'   => 275000,
                'satuan'       => 'pasang',
                'keterangan'   => 'Dudukan kompresor AC',
            ],
        ];

        foreach ($spareparts as $data) {
            Sparepart::updateOrCreate(
                ['kode_part' => $data['kode_part']],
                $data
            );
        }

        $this->command->info('✅  SparepartAcSeeder: ' . count($spareparts) . ' sparepart AC berhasil di-seed.');
    }
}
